apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
    serving.kserve.io/deploymentMode: RawDeployment
    serving.kserve.io/logLevel: "debug"  # Set log level to debug
  name: triton-is
spec:
  predictor:
    minReplicas: 1
    serviceAccountName: models-bucket-sa
    model:
      modelFormat:
        name: transformers
      runtime: triton-runtime
      resources:
        requests:
          cpu: "2"
          memory: "10Gi"  # Adjust this value
          nvidia.com/gpu: 1
        limits:
          cpu: "2"
          memory: "20Gi"    # Adjust this value
          nvidia.com/gpu: 1
      