kind: Secret
apiVersion: v1
metadata: 
  name: s3creds
  annotations:
    serving.kserve.io/s3-endpoint: minio-service.triton-inference-services.svc.cluster.local:9000
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-region: "us-east-1"
    serving.kserve.io/s3-usevirtualbucket: "false"
data: 
  AWS_ACCESS_KEY_ID: bWluaW8=
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM=
type: Opaque