apiVersion: "serving.kserve.io/v1alpha1"
kind: "TrainedModel"
metadata:
  name: "meta-llama-3-8b-instruct-awq"
spec:
  inferenceService: triton-is
  model:
    framework: transformers
    storageUri: s3://finalised-models/model-repository/meta-llama-3-8b-instruct-awq
    memory: "5Gi"  